### PR TITLE
init OEP-5 Non-fungible Token Standard

### PR DESCRIPTION
**Pull request by Avocas**

### CODE REVIEW

**Comment by nickfujita** [comment]
Is this still needed since OEP-8 was already approved?

**Comment by qiluge** [comment]
Is the from addr should be a parameter of transfer func and other func?

**Comment by Avocas** [comment]
OEP-8 is extends of OEP-4 and OEP-5, it can contain many assets, it services like games and others which need deploy many assets. OEP-4 and OEP-5 just services one asset, like fungible asset and non-fungible asset.

**Comment by javajoker** [comment]
published on ONT main net
contract hash: 4cfbe5d9e6b6d2e58f63b2883b26b540e0119c71

**Pull request merged**
