### PR TITLE
Cross contract call attack prevention

### PR DESCRIPTION
**Pull request by WyattMufson**
This OEP is meant to resolve the 3rd point of issue #46. It introduces a process for preventing malicious contracts to invoke smart contracts conforming to this OEP.

It is inspired by the article [An Analysis of Ontology Smart Contract Security and Loopholes — Part 1](https://medium.com/ontologynetwork/an-analysis-of-ontology-smart-contract-security-and-loopholes-part-1-f24c1680de67) and [the Caller Validation article by Tower Builders](https://learn.towerbuilders.org/#/smartContract/callerValidation).

### CODE REVIEW

**Comment by Honglei-Cong** [comment]
looks good to me

**Comment by laizy** [comment]
good to go.

**Comment by WyattMufson** [comment]
@laizy this has two approvals - can it be merged in?

Also what's the process to go from draft to accepted?

**Comment by laizy** [comment]
ping @tanZiWen

**Comment by tanZiWen** [comment]
`
def approveContract(addr, contractHash):

    RequireWallet(addr)
    RequireWitness(addr)
    RequireNotContract()
    key = getApprovalKey(addr, contractHash)
    Put(ctx, key, True)
`

i think `RequireWallet` is unnecessary.

**Comment by tanZiWen** [comment]
you means every user need to set the approve smart contract? whether the controler of smart contract 
set the whitelist is better than user. @WyattMufson

**Comment by tanZiWen** [comment]
if all user need to set the whitelist, i think it's difficult for them.

**Comment by WyattMufson** [comment]
@tanZiWen I updated the proposal and example contract

**Comment by tanZiWen** [comment]
i think you proposal is ok, but if it need to be merged to master, the proposal need a actual dApp who had use the proposal. @WyattMufson

**Comment by WyattMufson** [comment]
@tanZiWen does it need a dApp to be using it to be merged into master, or to be marked as accepted?

We're going to be including this in our NFT contract later this month.

**Comment by tanZiWen** [comment]
Great!

**Comment by WyattMufson** [comment]
@tanZiWen @Honglei-Cong @laizy we have a contract using this on the testnet at https://explorer.ont.io/contract/other/a47222204212ef759df954f1e1b156528098153d/10/1/testnet

We'll be launching one on the mainnet soon

**Comment by WyattMufson** [comment]
@tanZiWen @Honglei-Cong @laizy there is now a contract running on the mainnet using this: https://explorer.ont.io/contract/other/6585d17294994a0b16fb06b74bed8ae4051ea7c5/10/1

**Comment by Honglei-Cong** [comment]
This is ready to be merged, I think.

**Comment by WyattMufson** [comment]
@Honglei-Cong what should I update its status from `Draft` to? `Accepted` or `Final`?

**Comment by Honglei-Cong** [comment]
> @Honglei-Cong what should I update its status from `Draft` to? `Accepted` or `Final`?

Please update to 'Accepted'.  Thanks.

**Comment by WyattMufson** [comment]
@Honglei-Cong all set to go

**Pull request merged**
